"""``run-skill``-Tool: lets the Brain execute an installed user skill by name.

The Brain (Hauptjarvis Haiku + Sub-Jarvis Opus) can call this tool when a user
request clearly maps to one of the skills listed in the AVAILABLE SKILLS
section of the system prompt. The tool resolves the skill by name in the
process-wide ``SkillContext`` (set by the App-Layer at boot) and delegates
execution to the existing :class:`~jarvis.skills.runner.SkillRunner`.

Design notes:

* No bus events are published here. ``SkillRunner.run()`` already emits the
  full ``SkillStarted/StepExecuted/Completed/Failed`` lifecycle stream — see
  ``jarvis/skills/runner.py:174-326``. Re-emitting would double-count.
* ``SkillLifecycleState.DRAFT`` and ``DISABLED`` skills are rejected before
  the runner is touched (Plan-§AP-1: Constraint-Enforcement in code, not in
  prompt). DRAFTs may contain unsafe code generated by Sub-Jarvis-Authoring
  (Phase 7.5) — they must be promoted by the user first.
* ``risk_policy.default_tier == "block"`` is honoured immediately. The
  ``ask``-tier confirmation flow is intentionally NOT implemented here — the
  outer Tool-Use-Loop owns the general confirmation pipeline (see
  ``jarvis/safety/tool_executor.py``); a TODO marker keeps that boundary
  explicit.
* D9 Recursion-Protection: ``SkillRunner`` is constructed without a
  ``tool_registry`` reference everywhere in the codebase (verified in
  ``jarvis/ui/desktop_app.py:938``, ``jarvis/skills/cli.py:189``,
  and the test fixtures). A skill body that contains
  ``TOOL: run-skill {...}`` therefore fails-closed at
  ``SkillRunner._resolve_tool`` with ``tool 'run-skill' not found``.
"""
from __future__ import annotations

from typing import Any

from jarvis.core.protocols import ExecutionContext, ToolResult
from jarvis.skills.schema import SkillLifecycleState
from jarvis.skills.skill_context import try_get_skill_context


class RunSkillTool:
    """Brain-callable tool: execute a skill by name."""

    name: str = "run-skill"
    risk_tier: str = "monitor"
    description: str = (
        "Execute an installed user skill by name. Skills are pre-built workflows "
        "(routines, memory operations, focus modes). Use this tool when the user "
        "request clearly maps to one of the skills listed in the AVAILABLE SKILLS "
        "section."
    )
    schema: dict[str, Any] = {
        "type": "object",
        "properties": {
            "skill_name": {
                "type": "string",
                "description": "Exact skill name as listed in AVAILABLE SKILLS",
            },
            "args": {
                "type": "object",
                "description": "Optional arguments to pass to the skill body",
                "default": {},
            },
        },
        "required": ["skill_name"],
    }

    def __init__(self, *, bus: Any | None = None, manager: Any | None = None, **_: Any) -> None:
        # ``bus`` and ``manager`` are accepted for symmetry with other tool
        # constructors in the registry (factory.py instantiates tools with a
        # heterogeneous kwarg set). Both are unused here: the SkillRunner has
        # its own bus reference, and the SkillContext is the manager.
        self._bus = bus
        self._manager = manager

    async def execute(self, args: dict[str, Any], ctx: ExecutionContext) -> ToolResult:
        # Step 1 — argument validation
        raw_name = args.get("skill_name")
        if not isinstance(raw_name, str) or not raw_name.strip():
            return ToolResult(
                success=False,
                output=None,
                error="Missing required argument: skill_name",
            )
        skill_name = raw_name.strip()

        # Step 2 — process-wide SkillContext must be set
        skill_ctx = try_get_skill_context()
        if skill_ctx is None:
            return ToolResult(
                success=False,
                output=None,
                error="Skill subsystem not initialized",
            )

        # Step 3 — resolve skill
        try:
            skill = skill_ctx.registry.get(skill_name)
        except KeyError:
            return ToolResult(
                success=False,
                output=None,
                error=f"Unknown skill: {skill_name}",
            )

        # Step 4 — AP-1 enforcement: refuse DRAFT/DISABLED skills
        if skill.state == SkillLifecycleState.DRAFT:
            return ToolResult(
                success=False,
                output=None,
                error=(
                    f"Skill '{skill_name}' is in DRAFT state and not invocable. "
                    "Promote it first."
                ),
            )
        if skill.state == SkillLifecycleState.DISABLED:
            return ToolResult(
                success=False,
                output=None,
                error=(
                    f"Skill '{skill_name}' is DISABLED and not invocable. "
                    "Re-enable it first."
                ),
            )

        # Step 5 — risk-tier gate
        # Note: ``ask``-tier confirmation is OUT OF SCOPE for this MVP. The
        # outer Tool-Use-Loop's general confirmation pipeline already handles
        # ask-tier prompting at the Brain<->Tool boundary; wiring a second
        # confirmation here would create a double-prompt. TODO(skills-2):
        # honour skill-level ``ask``-tier explicitly when the executor exposes
        # a re-entrant confirmation API.
        tier: str = "monitor"
        if skill.frontmatter is not None:
            tier = skill.frontmatter.risk_policy.default_tier
        if tier == "block":
            return ToolResult(
                success=False,
                output=None,
                error="Skill is blocked by risk policy",
            )

        # Step 6 — delegate to SkillRunner (publishes lifecycle events itself)
        skill_args = args.get("args") or {}
        if not isinstance(skill_args, dict):
            skill_args = {}
        try:
            result = await skill_ctx.runner.run(skill, args=skill_args)
        except Exception as exc:  # noqa: BLE001
            return ToolResult(
                success=False,
                output=None,
                error=f"{type(exc).__name__}: {exc}",
            )

        # Step 7 — pack the result
        return ToolResult(
            success=result.success,
            output={
                "skill_name": skill_name,
                "rendered_body": result.rendered_body,
                "steps_count": len(result.steps),
                "duration_ms": result.duration_ms,
            },
            error=result.error,
        )
