/**
 * The only module that knows where figure files are. Everything else asks it
 * for the asset behind a recipe or a part id (docs/agent-society/character-pipeline.md §9.2).
 *
 * `catalog.json` is GENERATED by `scripts/figures/build_figures.py` — every
 * base and part with its style tags, slot, attach bone, default palette and
 * source credit — and the GLBs beside it are imported through Vite, so each
 * resolves to a fingerprinted URL and a rebuilt figure never serves stale.
 */
import catalogJson from "./catalog.json";

import type { FigureArchetype, FigureRecipe, Palette } from "./figureRecipe";

export interface CatalogBase {
  /** "biped/rogue" */
  id: string;
  file: string;
  archetype: FigureArchetype;
  variant: string;
  /** "rogue" — the value a recipe's `base` carries. */
  base: string;
  label: string;
  styles: string[];
  heightM: number;
  palette: Palette;
  source: string;
  license: string;
  triangles: number;
  clips: string[];
  height_m: number;
}

export interface CatalogPart {
  /** "headgear-knight-helmet" — the value a recipe's `parts[slot]` carries. */
  id: string;
  file: string;
  archetype: FigureArchetype;
  slot: string;
  attach: string;
  label: string;
  styles: string[];
  hides: string[];
  from_base: string;
  source: string;
  license: string;
  triangles: number;
}

export interface FigureCatalog {
  contract: number;
  styles: Record<string, string>;
  bases: CatalogBase[];
  parts: CatalogPart[];
}

export const CATALOG = catalogJson as FigureCatalog;

/** Every shipped GLB, keyed by its path under assets/society/figures/. */
const FILES = import.meta.glob("../../../assets/society/figures/**/*.glb", {
  query: "?url",
  import: "default",
  eager: true,
}) as Record<string, string>;

function urlForFile(file: string): string | null {
  const suffix = `/assets/society/figures/${file}`;
  for (const [key, url] of Object.entries(FILES)) {
    if (key.endsWith(suffix)) return url;
  }
  return null;
}

/** Base ids a recipe may still carry from before the catalog existed. */
const LEGACY_BASES: Record<string, string> = { medium: "rogue", small: "rogue", large: "rogue" };

export interface FigureAsset {
  url: string;
  archetype: FigureArchetype;
  base: string;
  defaultHeightM: number;
  palette: Palette | null;
  /** True when the base ships its hair as a second primitive that headgear may hide. */
  catalog: CatalogBase | null;
}

export function catalogBaseFor(recipe: Pick<FigureRecipe, "archetype" | "base">): CatalogBase | null {
  const base = LEGACY_BASES[recipe.base] ?? recipe.base;
  return CATALOG.bases.find((b) => b.archetype === recipe.archetype && b.base === base) ?? null;
}

/** The GLB behind a recipe: a catalog base, or the recipe's own imported model. */
export function figureAssetFor(
  recipe: Pick<FigureRecipe, "archetype" | "base"> & { model?: string; heightM?: number },
): FigureAsset | null {
  if (recipe.model) {
    return {
      url: recipe.model,
      archetype: recipe.archetype,
      base: recipe.base,
      defaultHeightM: recipe.heightM ?? 1.75,
      palette: null,
      catalog: null,
    };
  }
  const entry = catalogBaseFor(recipe);
  if (!entry) return null;
  const url = urlForFile(entry.file);
  if (!url) return null;
  return {
    url,
    archetype: entry.archetype,
    base: entry.base,
    defaultHeightM: entry.heightM,
    palette: entry.palette,
    catalog: entry,
  };
}

export interface PartAsset {
  url: string;
  part: CatalogPart;
}

export function partAssetFor(partId: string): PartAsset | null {
  const part = CATALOG.parts.find((p) => p.id === partId);
  if (!part) return null;
  const url = urlForFile(part.file);
  return url ? { url, part } : null;
}

/** The parts a recipe wears, resolved; unknown ids are dropped, not fatal. */
export function partAssetsFor(recipe: Pick<FigureRecipe, "parts">): PartAsset[] {
  return Object.values(recipe.parts ?? {})
    .map((id) => (id ? partAssetFor(id) : null))
    .filter((p): p is PartAsset => p !== null);
}

/** Styles that have at least one base today, in catalog order; the creator disables the rest. */
export function stylesWithBases(): string[] {
  const live = new Set(CATALOG.bases.flatMap((b) => b.styles));
  return Object.keys(CATALOG.styles).filter((s) => live.has(s));
}

export function basesForStyle(style: string | null, archetype: FigureArchetype = "biped"): CatalogBase[] {
  return CATALOG.bases.filter((b) => b.archetype === archetype && (!style || b.styles.includes(style)));
}

export function partsForSlot(slot: string, archetype: FigureArchetype = "biped", style: string | null = null): CatalogPart[] {
  return CATALOG.parts.filter(
    (p) => p.archetype === archetype && p.slot === slot && (!style || p.styles.includes(style)),
  );
}

/** Slots any catalog part fills for an archetype, in the contract's order of the parts list. */
export function slotsWithParts(archetype: FigureArchetype = "biped"): string[] {
  const seen: string[] = [];
  for (const p of CATALOG.parts) {
    if (p.archetype === archetype && !seen.includes(p.slot)) seen.push(p.slot);
  }
  return seen;
}

/** Every asset URL, for preloading the moment the section opens. */
export const FIGURE_URLS: readonly string[] = Object.values(FILES);

/**
 * Bases the creator can pick today, per archetype — keyed by the legacy
 * small/medium/large ids the dialog still offers. The catalog's own `base`
 * names (rogue, …) stay inside the catalog; this list is the dialog's.
 */
export const AVAILABLE_BASES: Readonly<Record<FigureArchetype, readonly string[]>> = {
  biped: ["medium"],
  quadruped: [],
  spirit: [],
};
